

package com.example.spring_security_mernis_auth.mernis.client;
//------------------------------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 9.3.3.2
//
// Created by Quasar Development 
//
// This class has been generated for test purposes only and cannot be used in any commercial project.
// To use it in commercial project, you need to generate this class again with Premium account.
// Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
//
// Licence: CBF65AD88AB8EB8E28E4A117F78D50051451F1A0D618F10197BF1A049F74D6E51112AB58AF2D6C89E49B9409B8C4735DE1BBE0B67C3C46D7ACFFD017F77CD244
//------------------------------------------------------------------------

public class DEASoapException extends java.lang.Exception
{
    private org.w3c.dom.Element _details=null;
    private Object _fault = null;
    
    public DEASoapException(String message,org.w3c.dom.Element details)
    {
        super(message);
        _details=details;
    }

    public DEASoapException(Object fault)
    {
        _fault=fault;
    }

    public Object getFault() {
        return _fault;
    }


    public org.w3c.dom.Element getDetails() {
        return _details;
    }
}