CREATE  TABLE users(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) UNIQUE  NOT NULL,
    password VARCHAR(255) UNIQUE NOT NULL,
    first_name VARCHAR(255)UNIQUE NOT NULL,
    last_name VARCHAR(255)UNIQUE NOT NULL,
    birth_year INT UNIQUE NOT NULL,
    identity_number BIGINT UNIQUE NOT NULL
)